const cars = [
  {
    id: 1,
    name: "Chevrolet Camaro",
    price: 43800,
    image: "/assets/products/ChevroletCamaro.jpg",
    engine: "V8 6.2L",
    horsepower: "453 CV",
    acceleration: "0-100 km/h en 4.3s",
    fuelConsumption: "12.8L/100km",
    fuelType: "gasolina", // Añadido
    rating: 4.5,
    color: "blanco",
    feature: "deportivo",
    transmission: "automatica",
    year: 2022,
    province: "Sevilla",
    km: 25000
  },
  {
    id: 2,
    name: "Opel Insignia",
    price: 11900,
    image: "/assets/products/OpelInsignia.jpg",
    engine: "1.6L Turbo",
    horsepower: "136 CV",
    acceleration: "0-100 km/h en 9.4s",
    fuelConsumption: "5.9L/100km",
    fuelType: "diesel", // Añadido
    rating: 4.0,
    color: "gris",
    feature: "familiar",
    transmission: "automatica",
    year: 2023,
    province: "Cádiz",
    km: 50000
  },
  {
    id: 3,
    name: "Ford Mustang",
    price: 55000,
    image: "/assets/products/FordMustang.jpg",
    engine: "V8 5.0L",
    horsepower: "450 CV",
    acceleration: "0-100 km/h en 4.1s",
    fuelConsumption: "13.5L/100km",
    fuelType: "gasolina", // Añadido
    rating: 4.8,
    color: "rojo",
    feature: "deportivo",
    transmission: "manual",
    year: 2024,
    province: "Granada",
    km: 10000
  },
  {
    id: 4,
    name: "BMW Serie 3",
    price: 25400,
    image: "/assets/products/BMW-Serie-3.png",
    engine: "2.0L Turbo",
    horsepower: "190 CV",
    acceleration: "0-100 km/h en 7.1s",
    fuelConsumption: "6.1L/100km",
    fuelType: "hibrido", // Añadido
    rating: 4.6,
    color: "negro",
    feature: "lujo",
    transmission: "automatica",
    year: 2021,
    province: "Córdoba",
    km: 75000
  },
  {
    id: 5,
    name: "Audi A4",
    price: 29800,
    image: "/assets/products/Audi-A4.jpg",
    engine: "2.0L TFSI",
    horsepower: "190 CV",
    acceleration: "0-100 km/h en 7.0s",
    fuelConsumption: "6.2L/100km",
    fuelType: "electrico", 
    rating: 4.4,
    color: "rojo oscuro",
    feature: "ejecutivo",
    transmission: "automatica",
    year: 2023,
    province: "Huelva",
    km: 40000
  },
  {
    id: 6,
    name: "Volkswagen Golf",
    price: 19700,
    image: "/assets/products/Volkswagen-Wolf.jpg",
    engine: "1.5L TSI",
    horsepower: "150 CV",
    acceleration: "0-100 km/h en 8.4s",
    fuelConsumption: "5.6L/100km",
    fuelType: "gasolina", // Añadido
    rating: 4.2,
    color: "gris metalizado",
    feature: "compacto",
    transmission: "manual",
    year: 2022,
    province: "Jaén",
    km: 30000
  },
  {
    id: 7,
    name: "Honda Civic",
    price: 20300,
    image: "/assets/products/Honda-Civic.jpg",
    engine: "1.5L Turbo",
    horsepower: "182 CV",
    acceleration: "0-100 km/h en 7.5s",
    fuelConsumption: "6.0L/100km",
    fuelType: "hibrido", 
    rating: 4.3,
    color: "azul",
    feature: "económico",
    transmission: "automatica",
    year: 2024,
    province: "Almería",
    km: 15000
  }
];

export default cars;